version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://db/pumpkinmind?serverTimezone=UTC
      MYSQL_USER: pumpkin
      MYSQL_PASSWORD: password
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; java -jar app.jar'
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: pumpkinmind
      MYSQL_USER: pumpkin
      MYSQL_PASSWORD: password